### ISSUE TITLE
已经提示

### ISSUE THREAD

**Issue by hcliu987** [starxg/RainbowBracketsCrack#1]
![image](https://github.com/starxg/RainbowBracketsCrack/assets/52879991/00c274e2-5cb0-4ed5-a3d8-3e98f392a00f)
![image](https://github.com/starxg/RainbowBracketsCrack/assets/52879991/513a2921-f6cb-436d-9790-ac70092e9995)

**Comment by starxg** [comment]
看样子插件并未生效，请检查插件目录是否正确。

参考：https://github.com/starxg/MyBatisCodeHelperProCrack/issues/1#issuecomment-1663230386

**Comment by hcliu987** [comment]
成功，放到了 plugin 需要在ja新建一个目录
