### ISSUE TITLE
Other IDE's support?

### ISSUE THREAD

**Issue by DoliTVD** [starxg/RainbowBracketsCrack#2]
This support other jetbrains ide's like pycharm?

**Comment by starxg** [comment]
yes. support

**Comment by DoliTVD** [comment]
so how to activate it?

**Comment by starxg** [comment]
edit your pycharm `idea.vmoptions`
```properties
--add-opens=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED
--add-opens=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED
-javaagent:/ja-netfilter-all-main/ja-netfilter.jar=jetbrains

# /ja-netfilter-all-main/ja-netfilter.jar https://github.com/libin9iOak/ja-netfilter-all
```

look at : https://github.com/starxg/MyBatisCodeHelperProCrack/issues/1#issuecomment-1663230386

**Comment by DoliTVD** [comment]
i have edited this file cuz i activate pycharm but this plugin is not activated
![image](https://github.com/starxg/RainbowBracketsCrack/assets/79114670/97af74bb-2053-4d43-a309-deac7880c6bb)
![image](https://github.com/starxg/RainbowBracketsCrack/assets/79114670/742c697e-b30c-42c7-9eaf-819b31f8a9c8)
![image](https://github.com/starxg/RainbowBracketsCrack/assets/79114670/91def4ac-ee2c-4d73-8d3a-bda39ab7a6a2)

**Comment by starxg** [comment]
Open PyCharm Settings

<img width="482" alt="image" src="https://github.com/starxg/RainbowBracketsCrack/assets/34997494/1f0ae6f1-2791-41f3-8482-fefa1e58d30c">

**Comment by DoliTVD** [comment]
oh ok thanks
